# Generated by Django 3.0.8 on 2020-07-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortenerURL',
        ),
    ]
